DROP TABLE IF EXISTS sbtest_users;
CREATE TABLE sbtest_users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    sequence_no INT,
    amount DECIMAL(10,2),
    rate FLOAT,
    score DOUBLE,
    is_active BOOLEAN,
    name VARCHAR(100),
    description TEXT,
    memo MEDIUMTEXT,
    char_code CHAR(3),
    created_at TIMESTAMP,
    updated_at DATETIME,
    birth_date DATE,
    work_time TIME,
    status VARCHAR(20),
    user_type VARCHAR(50),
    preferences VARCHAR(1000),
    PRIMARY KEY (id),
    INDEX idx_name (name),
    INDEX idx_status (status)
);

INSERT INTO sbtest_users (
    sequence_no,
    amount,
    rate,
    score,
    is_active,
    name,
    description,
    memo,
    char_code,
    created_at,
    updated_at,
    birth_date,
    work_time,
    status,
    user_type,
    preferences
) VALUES 
(
    1,
    2000.00,
    0.05,
    85.0,
    1,
    'テストユーザー1',
    '一般ユーザー1の説明',
    'メモ1',
    'JP1',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_DATE,
    '09:00:00',
    'ACTIVE',
    'USER',
    '{"lang": "ja", "theme": "dark"}'
),
(
    2,
    1500.00,
    0.03,
    70.0,
    0,
    'テストユーザー2',
    '管理者ユーザーの説明',
    'メモ2',
    'JP2',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_DATE,
    '10:00:00',
    'INACTIVE',
    'ADMIN,USER',
    '{"lang": "en", "theme": "light"}'
),
(
    3,
    3000.00,
    0.04,
    90.0,
    1,
    'テストユーザー3',
    '複雑クエリ用のユーザー',
    'メモ3',
    'JP3',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_DATE,
    '11:00:00',
    'ACTIVE',
    'VIP',
    '{"lang": "ja", "theme": "system"}'
);
